### ISSUE TITLE
Environment Detector doesn't see Valkyrien skies entites

### ISSUE THREAD

**Issue by Rostik2099** [IntelligenceModding/AdvancedPeripherals#651]
### Describe

As described in title. I want to use environment detector as radar, but it can't see any valkyrien skies entities.

### Steps to reproduce

Use scanEntities method

### Multiplayer?

No

### Version

1.18.2-0.7.31r (Latest 1.18.2)

### Minecraft, Forge and maybe other related mods versions

Forge 40.2.21 Minecraft 1.18.2

**Comment by zyxkad** [comment]
Dup IntelligenceModding/Advanced-Peripherals-Features#89
